# Generated by Django 3.2 on 2023-08-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_yaer_title_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Рейтинг'),
        ),
    ]
