# Generated by Django 3.2 on 2023-08-06 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка должна быть в диапазоне от 1 до 10'), django.core.validators.MaxValueValidator(10, message='Оценка должна быть в диапазоне от 1 до 10')], verbose_name='Оценка'),
        ),
    ]
